
type Relative @table {
  id: String! @default(expr: "uuidV4()")
  uid: String! @default(expr: "auth.uid")
  phone: String! @col(dataType: "varchar(15)")
}

type Snapshot @table {
  id: String! @default(expr: "uuidV4()")
  uid: String! @default(expr: "auth.uid")
  latitude: Float!
  longitude: Float!
  timestamp: Timestamp! @default(expr: "request.time")
}
