# --- CRUD for Relative ---

# Create a relative
mutation InsertRelative($uid: String!, $phone: String!) @auth(level: USER) {
  relative_insert(data: { uid: $uid, phone: $phone })
}

# Update a relative
mutation UpdateRelative($id: String!, $phone: String!) @auth(level: USER) {
  relative_update(key: { id: $id }, data: { phone: $phone })
}

# Delete a relative
mutation DeleteRelative($id: String!) @auth(level: USER) {
  relative_delete(key: { id: $id })
}

# --- CRUD for Snapshot ---

# Create a snapshot
mutation InsertSnapshot($uid: String!, $latitude: Float!, $longitude: Float!, $timestamp: Timestamp!) @auth(level: USER) {
  snapshot_insert(data: { uid: $uid, latitude: $latitude, longitude: $longitude, timestamp: $timestamp })
}

# Update a snapshot
mutation UpdateSnapshot($id: String!, $latitude: Float, $longitude: Float, $timestamp: Timestamp) @auth(level: USER) {
  snapshot_update(key: { id: $id }, data: { latitude: $latitude, longitude: $longitude, timestamp: $timestamp })
}

# Delete a snapshot
mutation DeleteSnapshot($id: String!) @auth(level: USER) {
  snapshot_delete(key: { id: $id })
}
